name: 'dbt_greenery'
version: '1.0.0'
config-version: 2

profile: 'greenery'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
dbt_greenery:
    staging:
      +materialized: view
    marts:
      +materialized: table

  post-hook:
    - "GRANT SELECT ON {{this}} TO reporting"

on-run-end:
  - "GRANT USAGE ON SCHEMA {{schema}} TO reporting"
